import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppMDXProvider } from "../domains/app-providers/app-mdx-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Not Working ! */}
        <AppMDXProvider>{children}</AppMDXProvider>
      </body>
    </html>
  );
}
